/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import org.eclipse.californium.elements.exception.ConnectorException;


public class App {

  public static String ENTRYPOINT = System.getenv("ENTRYPOINT");
  public static String MY_ROOM = System.getenv("MY_ROOM");
  public static String METADATA;

  static {
    try {
      METADATA = Files.readString(new File("/app/app/src/main/resources/metadata.ttl").toPath());
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  public static void main(String[] args) throws ConnectorException, IOException {
      new SensingAgent(ENTRYPOINT, METADATA, MY_ROOM).run();
  }
}
