/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import org.eclipse.californium.elements.exception.ConnectorException;


public class App {

    public static String ENTRYPOINT = "coap://localhost:5684";

    public static void main(String[] args) throws ConnectorException, IOException {
        if (args.length != 1) {
            new SensingAgent(ENTRYPOINT).run();
        } else {
            new SensingAgent(args[0]).run();
        }
    }
}
