services:
  organization_manager:
    build:
      context: ./OrgManager
    container_name: organization_manager
    #    environment:
    ports:
      - "7500:7500"
      - "5686:5686/udp"
    restart: always
    networks:
      - smart-buidling

  data_lake:
    container_name: data_lake
    hostname: datalake
    build:
      context: ./DataLake
    ports:
      - "7600:7600"
      - "5685:5685/udp"
    networks:
      - smart-buidling


  yggdrasil:
    build:
      context: ./Yggdrasil
      dockerfile: Dockerfile
    container_name: yggdrasil
    environment:
      - YGGDRASIL_VERSION=0.0.0
    ports:
      - "8080:8080"
      - "5683:5683/udp"
    networks:
      - smart-buidling
    restart: always

  automation_agent:
    build:
      context: ./AutomationAgent
    container_name: automation_agent
    environment:
      - AUTOMATION_AGENT_VERSION=0.0.0
      - YGGDRASIL_URL=http://yggdrasil:8080
    ports:
      - "8081:8081"
    networks:
      - smart-buidling
    restart: on-failure

  sensing_agent:
    build:
      context: ./SensingAgent
    container_name: sensing_agent
    environment:
      - ENTRYPOINT=coap://yggdrasil:5683/
    ports:
      - "8082:8082"
      - "5684:5684/udp"
    networks:
        - smart-buidling
    restart: on-failure

networks:
    smart-buidling:
        driver: bridge
