services:
  organization_manager:
    build:
      context: ./OrgManager
    container_name: organization_manager
    #    environment:
    ports:
      - "5683:5683/udp"
    restart: always
    networks:
      - smart-buidling

  db:
    container_name: db
    build:
      context: ./DB
    ports:
      - 7600:7600
    networks:
      - smart-buidling


  yggdrasil:
    image: yggdrasil:latest
    build:
      context: ./Yggdrasil
    container_name: yggdrasil
    environment:
      - YGGDRASIL_VERSION=0.0.0
    ports:
      - "8080:8080"
    networks:
      - smart-buidling
    restart: always

  AutomationAgent:
    image: automationagent:latest
    build:
      context: ./AutomationAgent
    container_name: automationAgent
    environment:
      - AUTOMATION_AGENT_VERSION=0.0.0
      - YGGDRASIL_URL=http://yggdrasil:8080
    ports:
      - "8898:8081"
    networks:
      - smart-buidling
    restart: on-failure

networks:
    smart-buidling:
        driver: bridge
